language: python
python: 3.5
branches:
  only:
    - src

install:
  - pip install -r requirements.txt

script:
  - sphinx-build . _build

after_success:
  - export DATE=$(date '+%Y-%m-%d %T')
  - ghp-import -m "Last update at $DATE" -b master _build
  - git push -fq "https://$GH_TOKEN@github.com/nengo/nengo.github.io.git" master
