language: python
python: 3.6

install:
  - pip install -r requirements.txt

script:
  - sphinx-build -W . _build

after_success:
  - if [[ $TRAVIS_BRANCH == 'src' ]]; then
      export DATE=$(date '+%Y-%m-%d %T');
      git config --global user.email "travis@travis-ci.org";
      git config --global user.name "TravisCI";
      ghp-import -m "Last update at $DATE" -c "www.nengo.ai" -b master _build;
      git push -fq "https://$GH_TOKEN@github.com/nengo/nengo.github.io.git" master;
    fi
